apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bdmonedas-sfs-tt
spec:
  serviceName: "bdmonedas-servicio"
  replicas: 1
  selector:
    matchLabels:
      app: bdmonedas
  template: 
    metadata:
      labels:
        app: bdmonedas
    spec: 
      containers:
        - name: bdmonedas
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "monedas"
            - name: POSTGRES_USUARIO
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:                     # ✅ CORRECTO
                secretKeyRef:
                  name: bdmonedas-secretos-tt
                  key: BDMONEDAS_PASSWORD
          volumeMounts:
            - name: storage-dbmonedas
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: storage-dbmonedas
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: bdmonedas-sc